apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-consumer
  namespace: sopes1
spec:
  selector:
    matchLabels:
      name: deploy-consumer
  replicas: 1
  template:
    metadata:
      labels:
        name: deploy-consumer
    spec:
      containers:
        - name: consumer
          image: henrrybran/consumer:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: secret-env-consumer
                  key: PORT
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: secret-env-consumer
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC
              valueFrom:
                secretKeyRef:
                  name: secret-env-consumer
                  key: KAFKA_TOPIC
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-env-consumer
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-env-consumer
                  key: REDIS_PASSWORD
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secret-env-consumer
                  key: MONGO_URI
