apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-grpcclient
  namespace: sopes1
spec:
  selector:
    matchLabels:
      name: deploy-grpcclient
  replicas: 1
  template:
    metadata:
      labels:
        name: deploy-grpcclient
    spec:
      containers:
        - name: grpcclient
          image: henrrybran/grpcclient:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: secret-env-grpcclient
                  key: PORT
            - name: PORT_SERVER
              valueFrom:
                secretKeyRef:
                  name: secret-env-grpcclient
                  key: PORT_SERVER
            - name: IP_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-env-grpcclient
                  key: IP_HOST
