apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deploy-consumer-autoscaler
  namespace: sopes1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-consumer
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
