apiVersion: v1
kind: Service
metadata:
  namespace: sopes1
  name: service-consumer
spec:
  ports:
    - name: consumer-port
      port: 3002
      targetPort: 3002
  selector:
    name: deploy-consumer
  type: NodePort
