apiVersion: v1
kind: Service
metadata:
  namespace: sopes1
  name: service-producer
spec:
  ports:
    - name: producer-port
      port: 3002
      targetPort: 3002
  selector:
    name: deploy-producer
  type: LoadBalancer
