apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: sopes1
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "redis",
                "orgId": 1,
                "password":"YOUR_PASSWORD",
                "type": "redis",
                "url": "redis://redis.sopes1.svc:6379",
                "version": 1
            }
        ]
    }
