apiVersion: v1
kind: Secret
metadata:
  name: secret-env-consumer
  namespace: sopes1
type: Opaque
data:
  PORT: "MzAwMg==" #3002
  KAFKA_BROKERS: "bXktY2x1c3Rlci1rYWZrYS1ib290c3RyYXA6OTA5Mg==" #my-cluster-kafka-bootstrap:9092
  KAFKA_TOPIC: "dG9waWMtc29wZXMx" #topic-sopes1
  REDIS_HOST: "cmVkaXM=" #redis
  REDIS_PASSWORD: "WU9VUl9QQVNTV09SRA==" #YOUR_PASSWORD
  MONGO_URI: "bW9uZ29kYjovL21vbmdvZGI6MjcwMTc=" #mongodb://mongodb:27017

#Los valores de las variables de entorno se deben codificar a base 64
